### ISSUE TITLE
The fittings are crashed for some reason in loop 2

### ISSUE THREAD

**Issue by liuxiaolan2018** [PeterKamphuis/pyFAT-astro#7] opened 2022-07-12 03:54 UTC
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry NGC5055_20220707_Jy.
        Which is the galaxy in directory /home/lxl/ngc5055/reduced/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is fp and xp are not of the same length..
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        
            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to: 

            https://github.com/PeterKamphuis/pyFAT/issues 

            If the error occured while fitting a galaxy, please attach your fitting log as well
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/main.py", line 376, in main
    current_run = runf.fitting_osc(Configuration,Fits_Files,Tirific_Template,Initial_Parameters)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/run_functions.py", line 589, in fitting_osc
    current_run = one_step_converge(Configuration, Fits_Files,Tirific_Template,current_run,debug = Configuration['DEBUG'])
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/run_functions.py", line 833, in one_step_converge
    accepted_size = check_size(Configuration,Tirific_Template, fit_type = fit_type, stage = stage, current_run = current_run, debug=debug,Fits_Files=Fits_Files)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/modify_template.py", line 333, in check_size
    set_new_size(Configuration,Tirific_Template,Fits_Files,fit_type= fit_type, stage = stage ,debug = debug,current_run = current_run)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/modify_template.py", line 2435, in set_new_size
    parameters[i] = list(np.interp(np.array(radii,dtype=float),np.array(old_radii,dtype=float),np.array(parameters[i],dtype=float)))
  File "<__array_function__ internals>", line 5, in interp
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/numpy/lib/function_base.py", line 1439, in interp
    return interp_func(x, xp, fp, left, right)

**Comment by PeterKamphuis** [comment] 2022-07-12 09:39
Yes this is a bug. I think it should be fixed in the branch pyFAT could you try that?

**Comment by liuxiaolan2018** [comment] 2022-07-13 01:23
Dear Peter,
Thank you for your prompt reply. I will have a try. Thank you very much.

**Comment by PeterKamphuis** [comment] 2022-07-13 07:06
Let me know how it goes.

**Comment by liuxiaolan2018** [comment] 2022-07-13 07:48
Yes, it just stop like this.
(hifast_env) lxl@lxl:~/ngc5055/reduced$ pyFAT cube_name=NGC5055_20220707_Jy.fits
        We are starting the catalogue entry NGC5055_20220707_Jy in the directory ./.

        RUN_TIRIFIC: 50.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 50.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 50.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/fits_functions.py:763: RuntimeWarning: All-NaN slice encountered
  hdr2D['DATAMAX'] = np.nanmax(moment1)
        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry NGC5055_20220707_Jy.
        Which is the galaxy in directory /home/lxl/ngc5055/reduced/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is: "Floating point nan values are not allowed in FITS headers.".
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        
            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to: 

            https://github.com/PeterKamphuis/pyFAT/issues 

            If the error occured while fitting a galaxy, please attach your fitting log as well

Traceback (most recent call last):
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/FAT_Galaxy_Loops.py", line 231, in FAT_Galaxy_Loops
    cf.finish_galaxy(Configuration, current_run=current_run,
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/clean_functions.py", line 580, in finish_galaxy
    make_moments(Configuration,Fits_Files,fit_type = 'Generic_Final',vel_unit = 'm/s',debug=debug)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/fits_functions.py", line 763, in make_moments
    hdr2D['DATAMAX'] = np.nanmax(moment1)
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/astropy/io/fits/header.py", line 207, in __setitem__
    self._update((key, value, comment))
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/astropy/io/fits/header.py", line 1652, in _update
    existing_card.value = value
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/astropy/io/fits/card.py", line 325, in value
    raise ValueError("Floating point {!r} values are not allowed "
ValueError: Floating point nan values are not allowed in FITS headers.

**Comment by liuxiaolan2018** [comment] 2022-07-13 07:51
Dear peter,
There is another problem, when I run pyFAT using the catalogue file or the  configuration file. The error is like this:

(hifast_env) lxl@lxl:~/ngc5055/reduced$ pyFAT input.catalogue=Input_Catalogue.txt
Traceback (most recent call last):
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/main.py", line 155, in main
    Full_Catalogue = rf.catalogue(Original_Configuration['CATALOGUE'])
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/Support/read_functions.py", line 55, in catalogue
    Catalogue[key].append(float(input[i]))
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxl/hifast_env/bin/pyFAT", line 10, in <module>
    main.main(sys.argv[1:])
  File "/home/lxl/hifast_env/lib/python3.9/site-packages/pyFAT_astro/main.py", line 217, in main
    raise ProgramError(f'''Something went wrong in the main. This should not happen. Please list an issue on github.''')
pyFAT_astro.Support.fat_errors.ProgramError: Something went wrong in the main. This should not happen. Please list an issue on github.

**Comment by PeterKamphuis** [comment] 2022-07-13 09:17
The first error seems to come from the header of your input.  It seems the fitting has been done but that the moment maps can not be created. As it crashes on the moment1 it seems there is an issue in how you defined your third (velocity) axis. 

Could you post or email me the header of the Finalmodel.fits file in the directory Finalmodel

The second error seems to be related to how you build the catalogue. Did you use | or a space to separate the columns? It should be |. I can fix it to allow for spaces the | is a left over from the IDL FAT.

**Comment by PeterKamphuis** [comment] 2022-07-13 09:23
Actually for the catalogue it seems that you have not classified all columns or not filled all the columns in the input.

**Comment by PeterKamphuis** [comment] 2022-07-13 10:22
I build in a check on the catalogue such that all required columns are checked to be read correctly.

**Comment by liuxiaolan2018** [comment] 2022-07-13 10:40
Dear peter,
For the first problem, I am so sorry about that the Finalmodel.fits file was cleaned because I run a new process. Yes, I note the problem may be in the header of my data. The unit of the velocity axis is km/s, not m/s. So, I update the header of the data to m/s in the third axis. And this process is still running. I haven't gotten a new one. 
Also, I create the catalogue file by  replacing the corresponding column in the FAT_Example_Catalogue.txt, like this 
id|distance|directoryname|cubename
0|8.99|/home/lxl/ngc5055/reduced/|NGC5055_20220707_Jy

**Comment by PeterKamphuis** [comment] 2022-07-13 10:58
Well FAT should be able to detect the km/s and transform it into m/s so that should not be the problem. But I am not sure what is the problem. From your error it seems that your moment1 map is all empty but to get there the moment0 map should be created so the mask or the cube should not be the issue.

The catalogue looks fine as well so I am not entirly sure there either,  the only thing that you might change is that the directory should branch from the main directory in principle. With the defaults the main_directory is where you start pyFAT. If the cube is in that directory for the directory name should be ./

So if you start pyFAT in   /home/lxl/ngc5055/ then in the catalogue you should have reduced as the directory name. I don't see how that resulted in that specific error though. I'll try to reproduce it later today.

**Comment by PeterKamphuis** [comment] 2022-07-13 11:14
Ok I suspect that in your catalogue you have an empty line at the end. I build in a check for that now. If you update the pyFAT branch that should work now.

**Comment by liuxiaolan2018** [comment] 2022-07-13 11:31
Well received and Thanks a lot. I will update the pyFAT now and have a try later.

**Comment by PeterKamphuis** [comment] 2022-07-13 11:35
Thank you for helping to debug.

**Comment by liuxiaolan2018** [comment] 2022-07-13 11:39
Yes, there is no problem to run pyFAT using the catalogue file now. Thank you so much.

**Comment by liuxiaolan2018** [comment] 2022-07-13 11:41
I also really appreciate you for helping me. Many thanks.

**Comment by liuxiaolan2018** [comment] 2022-07-14 02:27
Dear Peter,
Thank you. I am writing to inform you that I succeed in the pyFAT fittings to the available WSRT data.The pyFAT should has no problem to fit the cube data. Yet, I also met a problem in fitting my cube data, which I guess came to my header of the data. Now I am trying to resolve the problem by updating the header of the cube data. Attached is the problem below:

       We are starting the catalogue entry NGC5055_20220707_Jy_U in the directory ./.

        RUN_TIRIFIC: 60.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 60.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 60.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 85.7 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 75.0 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 62.5 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        RUN_TIRIFIC: 62.5 % Completed 

        RUN_TIRIFIC: Finished the current tirific run.
        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry NGC5055_20220707_Jy_U.
        Which is the galaxy in directory /home/lxl/ngc5055/reduced/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is: "WCS has more than 2 pixel dimensions, so 'slices' should be set".
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        
            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to: 

            https://github.com/PeterKamphuis/pyFAT/issues 

            If the error occured while fitting a galaxy, please attach your fitting log as well

Traceback (most recent call last):
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/pyFAT_astro-0.0.9-py3.8.egg/pyFAT_astro/FAT_Galaxy_Loops.py", line 231, in FAT_Galaxy_Loops
    cf.finish_galaxy(Configuration, current_run=current_run,
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/pyFAT_astro-0.0.9-py3.8.egg/pyFAT_astro/Support/clean_functions.py", line 581, in finish_galaxy
    make_overview_plot(Configuration,Fits_Files,debug=debug)
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/pyFAT_astro-0.0.9-py3.8.egg/pyFAT_astro/Support/write_functions.py", line 607, in make_overview_plot
    ax_PV = Overview.add_subplot(gs[2:8,8:14], projection=xv_proj)
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/matplotlib/figure.py", line 772, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/astropy/visualization/wcsaxes/core.py", line 119, in __init__
    self.reset_wcs(wcs=wcs, slices=slices, transform=transform, coord_meta=coord_meta)
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/astropy/visualization/wcsaxes/core.py", line 369, in reset_wcs
    transform, coord_meta = transform_coord_meta_from_wcs(self.wcs, self.frame_class, slices=slices)
  File "/home/lxl/software/anaconda3/lib/python3.8/site-packages/astropy/visualization/wcsaxes/wcsapi.py", line 31, in transform_coord_meta_from_wcs
    raise ValueError("WCS has more than 2 pixel dimensions, so "
ValueError: WCS has more than 2 pixel dimensions, so 'slices' should be set

**Comment by PeterKamphuis** [comment] 2022-07-14 05:34
Yes, I saw this yesterday late already. It should be fixed in pyFAT. Try updating the branch.

**Closed** 2022-07-19 00:40 UTC
