### ISSUE TITLE
Error suspected to be because empty FAT cubes created on using sofia_catalogue 

### ISSUE THREAD

**Issue by 3rico** [PeterKamphuis/pyFAT-astro#6] opened 2022-01-19 07:20 UTC
On setting
```
fitting:
catalogue_start_id: '-1'
catalogue_end_id: '-1'
fitting_stages:

   create_fat_cube 
   sofia_catalogue
   existing_sofia
   fit_tirific_osc

```
And running pyFAT, I stumble upon the error shown below. Upon following up it seems that the FAT cubes made by pyFAT from sofia cubelets appear to be empty, possibly because in line
```
/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py:1177
'create_fat_cube' is not in Configuration['FITTING_STAGES'] 

```
As it had been removed previously in line:
```
/home/brenda/pyFAT-astro/pyFAT_astro/Support/support_functions.py:2871
Configuration['FITTING_STAGES'].remove('create_fat_cube')

```
but I could be wrong...

```

        CLEANUP: We are cleaning the following directories:
        CLEANUP: Finalmodel,Fit_Tirific_OSC
        CLEANUP: and the following files:
        CLEANUP: tclean_image_4_beam_corrected_flipped_channels_1_FAT-Basic_Info.txt,tclean_image_4_beam_corrected_flipped_channels_1_FAT_opt.fits,Fit_Tirific_OSC_In.def

        We are in loop 0. This is catalogue entry 1 and the directory tclean_image_4_beam_corrected_flipped_channels_FAT_cubelets/tclean_image_4_beam_corrected_flipped_channels_1.

        GUESS_ORIENTATION: starting extraction of initial parameters.

  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/ipdb/__main__.py", line 327, in <module>
    main()
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/brenda/anaconda3/envs/py37/bin/pyFAT", line 3, in <module>
    __requires__ = 'pyFAT-astro==0.0.8'
  File "/home/brenda/pyFAT-astro/bin/pyFAT", line 7, in <module>
    main.main(sys.argv[1:])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 368, in main
    Initial_Parameters = runf.check_source(Configuration, Fits_Files,debug=Configuration['DEBUG'])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/run_functions.py", line 395, in check_source
    pa, inclination, SBR_initial, maj_extent,x_new,y_new,new_vsys,VROT_initial = rf.guess_orientation(Configuration,Fits_Files, center = [x,y],debug=debug)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py", line 363, in guess_orientation
    SNR = np.nanmean(map[noise_map > 0.]/noise_map[noise_map > 0.])
  File "<__array_function__ internals>", line 6, in nanmean
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 956, in nanmean
    warnings.warn("Mean of empty slice", RuntimeWarning, stacklevel=3)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/warnings.py", line 110, in _showwarnmsg
    msg.file, msg.line)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 39, in warn_with_traceback
    traceback.print_stack(file=log)
/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py:363: RuntimeWarning: Mean of empty slice
  SNR = np.nanmean(map[noise_map > 0.]/noise_map[noise_map > 0.])
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/ipdb/__main__.py", line 327, in <module>
    main()
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/brenda/anaconda3/envs/py37/bin/pyFAT", line 3, in <module>
    __requires__ = 'pyFAT-astro==0.0.8'
  File "/home/brenda/pyFAT-astro/bin/pyFAT", line 7, in <module>
    main.main(sys.argv[1:])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 368, in main
    Initial_Parameters = runf.check_source(Configuration, Fits_Files,debug=Configuration['DEBUG'])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/run_functions.py", line 395, in check_source
    pa, inclination, SBR_initial, maj_extent,x_new,y_new,new_vsys,VROT_initial = rf.guess_orientation(Configuration,Fits_Files, center = [x,y],debug=debug)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py", line 367, in guess_orientation
    median_noise_in_map = np.nanmedian(noise_map[noise_map > 0.])
  File "<__array_function__ internals>", line 6, in nanmedian
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 1113, in nanmedian
    return np.nanmean(a, axis, out=out, keepdims=keepdims)
  File "<__array_function__ internals>", line 6, in nanmean
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 956, in nanmean
    warnings.warn("Mean of empty slice", RuntimeWarning, stacklevel=3)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/warnings.py", line 110, in _showwarnmsg
    msg.file, msg.line)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 39, in warn_with_traceback
    traceback.print_stack(file=log)
/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1113: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/ipdb/__main__.py", line 305, in main
    pdb._runscript(mainpyfile)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/brenda/anaconda3/envs/py37/bin/pyFAT", line 3, in <module>
    __requires__ = 'pyFAT-astro==0.0.8'
  File "/home/brenda/pyFAT-astro/bin/pyFAT", line 7, in <module>
    main.main(sys.argv[1:])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 368, in main
    Initial_Parameters = runf.check_source(Configuration, Fits_Files,debug=Configuration['DEBUG'])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/run_functions.py", line 395, in check_source
    pa, inclination, SBR_initial, maj_extent,x_new,y_new,new_vsys,VROT_initial = rf.guess_orientation(Configuration,Fits_Files, center = [x,y],debug=debug)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py", line 367, in guess_orientation
    median_noise_in_map = np.nanmedian(noise_map[noise_map > 0.])
  File "<__array_function__ internals>", line 6, in nanmedian
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 1113, in nanmedian
    return np.nanmean(a, axis, out=out, keepdims=keepdims)
  File "<__array_function__ internals>", line 6, in nanmean
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 956, in nanmean
    warnings.warn("Mean of empty slice", RuntimeWarning, stacklevel=3)
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/warnings.py", line 110, in _showwarnmsg
    msg.file, msg.line)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 39, in warn_with_traceback
    traceback.print_stack(file=log)
/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py:1113: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry 1.
        Which is the galaxy in directory /home/maina/vault-ike/PKS_2020_Abhisek/Full_cube/sofia_tclean_image_4_beam_corrected_flipped_channels/tclean_image_4_beam_corrected_flipped_channels_FAT_cubelets/tclean_image_4_beam_corrected_flipped_channels_1/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is zero-size array to reduction operation fmin which has no identity.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

        
            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to: 

            https://github.com/PeterKamphuis/pyFAT/issues 

            If the error occured while fitting a galaxy, please attach your fitting log as well

  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 368, in main
    Initial_Parameters = runf.check_source(Configuration, Fits_Files,debug=Configuration['DEBUG'])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/run_functions.py", line 395, in check_source
    pa, inclination, SBR_initial, maj_extent,x_new,y_new,new_vsys,VROT_initial = rf.guess_orientation(Configuration,Fits_Files, center = [x,y],debug=debug)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py", line 368, in guess_orientation
    minimum_noise_in_map = np.nanmin(noise_map[noise_map > 0.])
  File "<__array_function__ internals>", line 6, in nanmin
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 321, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)
The program exited via sys.exit(). Exit status: 1
```

Error from Log.txt

```
This file is a log of the fitting process run at 2022-01-19 09:05:48.701203.
        This is version v0.0.8 of the program.
        CLEANUP: We are cleaning the following directories:
        CLEANUP: Finalmodel,Fit_Tirific_OSC
        CLEANUP: and the following files:
        CLEANUP: tclean_image_4_beam_corrected_flipped_channels_1_FAT-Basic_Info.txt,tclean_image_4_beam_corrected_flipped_channels_1_FAT_opt.fits,Fit_Tirific_OSC_In.def
        We are in loop 0. This is catalogue entry 1 and the directory tclean_image_4_beam_corrected_flipped_channels_FAT_cubelets/tclean_image_4_beam_corrected_flipped_channels_1.
        CUT_CUBES: Your input cube is significantly larger than the detected source.
        CUT_CUBES: we will cut to x-axis = [127,41] y-axis = [40,43]
        CUT_CUBES: z-axis = [127,41].
        CUT_CUBES: We will cut the following files:
        CUT_CUBES: tclean_image_4_beam_corrected_flipped_channels_1_FAT.fits, Sofia_Output/tclean_image_4_beam_corrected_flipped_channels_1_FAT_mask.fits, Sofia_Output/tclean_image_4_beam_corrected_flipped_channels_1_FAT_mom0.fits, Sofia_Output/tclean_image_4_beam_corrected_flipped_channels_1_FAT_mom1.fits, Sofia_Output/tclean_image_4_beam_corrected_flipped_channels_1_FAT_mom2.fits, Sofia_Output/tclean_image_4_beam_corrected_flipped_channels_1_FAT_chan.fits
        OPTIMIZED_CUBE: Your input cube has 3.7734515899529817 pixels along the minor FWHM.
        OPTIMIZED_CUBE: You requested 4 but we cannot improve the resolution.
        OPTIMIZED_CUBE: We are using the pixel size of the original cube.
        CHECK_SOURCE: The source finder found the following center in pixels.
        CHECK_SOURCE: RA center = 40.29093900000001 with boundaries 30, 50
        CHECK_SOURCE: DEC center = 41.66323800000001 with boundaries 30, 52
        CHECK_SOURCE: V_sys center = 28.436361000000034 with boundaries 6, 48
        CHECK_SOURCE: This should correspond to the WCS coordinates:
        CHECK_SOURCE: RA center = 306.182844 deg or 20h24m43.88  with boundaries 306.0742294286902,306.0881881594992
        CHECK_SOURCE: DEC center = -37.161391 deg  or -37d9m41.01  with boundaries -37.13524516662579,-37.12303903241675
        CHECK_SOURCE: Sofia V_sys center = 11544.60 with boundaries 20771.054329631625,21002.602786570304
        GUESS_ORIENTATION: starting extraction of initial parameters.
        FINISH_CURRENT_RUN: Is Tirific Running? False. 
        FINISH_CURRENT_RUN: No run is initialized. 
        CHECK_LEGITIMACY: An unspecified error is registered. The final message should reflect this.
        ------------When filing a bug report please copy all output  below this line------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        FAT did not run the full fitting routines for catalog entry 1.
        Which is the galaxy in directory /home/maina/vault-ike/PKS_2020_Abhisek/Full_cube/sofia_tclean_image_4_beam_corrected_flipped_channels/tclean_image_4_beam_corrected_flipped_channels_FAT_cubelets/tclean_image_4_beam_corrected_flipped_channels_1/.
        Please check this log and output_catalogue carefully for what went wrong.
        The detected exit reason is zero-size array to reduction operation fmin which has no identity.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        
            Your code has crashed for some reason. If this message completely baffles you then please submit the trace back as a bug report to: 

            https://github.com/PeterKamphuis/pyFAT/issues 

            If the error occured while fitting a galaxy, please attach your fitting log as well
  File "/home/brenda/pyFAT-astro/pyFAT_astro/main.py", line 368, in main
    Initial_Parameters = runf.check_source(Configuration, Fits_Files,debug=Configuration['DEBUG'])
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/run_functions.py", line 395, in check_source
    pa, inclination, SBR_initial, maj_extent,x_new,y_new,new_vsys,VROT_initial = rf.guess_orientation(Configuration,Fits_Files, center = [x,y],debug=debug)
  File "/home/brenda/pyFAT-astro/pyFAT_astro/Support/read_functions.py", line 368, in guess_orientation
    minimum_noise_in_map = np.nanmin(noise_map[noise_map > 0.])
  File "<__array_function__ internals>", line 6, in nanmin
  File "/home/brenda/anaconda3/envs/py37/lib/python3.7/site-packages/numpy/lib/nanfunctions.py", line 321, in nanmin
    res = np.fmin.reduce(a, axis=axis, out=out, **kwargs)

```

**Comment by PeterKamphuis** [comment] 2022-01-19 09:02
This seems to be caused by the lack of a channel map. It would normally not be necessary from the SoFiA output if pyFAT had a mask it should create one. I'll try to fix this.

**Comment by PeterKamphuis** [comment] 2022-01-19 13:06
Hi Eric,

I'm a bit confused by your statement "And running pyFAT, I stumble upon the error shown below. Upon following up it seems that the FAT cubes made by pyFAT from sofia cubelets appear to be empty, possibly because in line." 

 What do you mean with the FAT Cubes appear empty? They should be merely copied from the SoFiA output. Can you check that the SoFiA output has proper sources in each cube?  I also noticed that the channel map was not properly erased before copying I have remedied this in the branch Issue_6 but a way around this would be to simply remove the FAT_cubelets directory to ensure to start from the proper SoFiA output. Could you try that and let me know how it goes.

**Comment by PeterKamphuis** [comment] 2022-01-19 13:18
Nevermind, I found that you are right, there is an error in the copying of the cube somehow. I will trace it and fix it.

**Comment by PeterKamphuis** [comment] 2022-01-19 15:20
Ok, the problem was that the pixel coordinates in the catalogues were not properly transformed to the cubelet values. This should now be fixed in the branch Issue_6

**Comment by PeterKamphuis** [comment] 2022-01-21 07:27
Did this fix work?

**Comment by 3rico** [comment] 2022-01-21 07:52
This fix on branch issue6 works perfectly!! It's the one I'll be using by
default for now thank you!

**Comment by PeterKamphuis** [comment] 2022-01-21 07:59
Great I'll work it into the next release then.

**Closed by PeterKamphuis** 2022-01-21 07:59 UTC
